import Layout from "@/components/layout/Layout";

const Terms = () => {
  return (
    <Layout>
      <section className="py-16">
        <div className="container-custom max-w-4xl">
          <h1 className="font-display text-4xl font-bold text-foreground mb-8">
            Terms of Service
          </h1>
          
          <div className="prose prose-lg dark:prose-invert">
            <p className="text-muted-foreground mb-6">
              <strong>Last updated:</strong> {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Acceptance of Terms
            </h2>
            <p className="text-muted-foreground mb-6">
              By accessing and using Psych Report Assistant ("the Service"), you accept and agree 
              to be bound by these Terms of Service. If you do not agree to these terms, please 
              do not use the Service.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Description of Service
            </h2>
            <p className="text-muted-foreground mb-6">
              Psych Report Assistant provides a free online tool that allows users to generate 
              psychological assessment reports from Q-Global export data. The Service processes 
              data entirely within the user's web browser and does not transmit or store user data 
              on our servers.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              User Responsibilities
            </h2>
            <p className="text-muted-foreground mb-4">As a user of this Service, you agree to:</p>
            <ul className="list-disc pl-6 text-muted-foreground mb-6 space-y-2">
              <li>Use the Service only for lawful purposes and in accordance with these Terms</li>
              <li>Ensure you have proper authorization to access and process any data you upload</li>
              <li>Maintain compliance with all applicable laws, including HIPAA, FERPA, and other 
              privacy regulations relevant to your jurisdiction and profession</li>
              <li>Take responsibility for the accuracy and appropriateness of generated reports</li>
              <li>Not attempt to reverse engineer, modify, or interfere with the Service</li>
            </ul>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Professional Use Disclaimer
            </h2>
            <p className="text-muted-foreground mb-6">
              The reports generated by this Service are tools to assist qualified professionals. 
              Users must review, verify, and take professional responsibility for all generated 
              content before use. The Service does not replace professional judgment, clinical 
              interpretation, or ethical obligations.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Intellectual Property
            </h2>
            <p className="text-muted-foreground mb-6">
              The Service, including its design, features, and content (excluding user-uploaded data), 
              is owned by Psych Report Assistant and protected by intellectual property laws. 
              Q-Global is a trademark of Pearson Education, Inc. We are not affiliated with, 
              endorsed by, or sponsored by Pearson.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Disclaimer of Warranties
            </h2>
            <p className="text-muted-foreground mb-6">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, 
              EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, 
              ERROR-FREE, OR COMPLETELY SECURE. USE OF THE SERVICE IS AT YOUR OWN RISK.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Limitation of Liability
            </h2>
            <p className="text-muted-foreground mb-6">
              TO THE FULLEST EXTENT PERMITTED BY LAW, PSYCH REPORT ASSISTANT SHALL NOT BE LIABLE 
              FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING 
              FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO ERRORS IN GENERATED 
              REPORTS, DATA LOSS, OR UNAUTHORIZED ACCESS TO YOUR LOCAL DATA.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Premium Products
            </h2>
            <p className="text-muted-foreground mb-6">
              Purchases of our premium desktop version are processed through Payhip and subject 
              to their terms of service. Refund policies and licensing terms for premium products 
              are provided at the time of purchase.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Modifications to Service
            </h2>
            <p className="text-muted-foreground mb-6">
              We reserve the right to modify, suspend, or discontinue the Service at any time 
              without notice. We may also update these Terms from time to time. Continued use 
              of the Service after changes constitutes acceptance of the modified Terms.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Governing Law
            </h2>
            <p className="text-muted-foreground mb-6">
              These Terms shall be governed by and construed in accordance with the laws of 
              the United States, without regard to conflict of law principles.
            </p>

            <h2 className="font-display text-xl font-semibold text-foreground mt-8 mb-4">
              Contact Information
            </h2>
            <p className="text-muted-foreground mb-6">
              For questions about these Terms, please contact us via our{" "}
              <a href="/contact" className="text-primary hover:underline">Contact Form</a>.
            </p>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default Terms;
