import { Layout } from "@/components/layout";

export default function Terms() {
  return (
    <Layout>
      <section className="py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          <h1 className="text-3xl md:text-5xl font-bold mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: December 6, 2024</p>
          <div className="prose prose-invert prose-lg max-w-none prose-p:text-muted-foreground prose-headings:text-foreground prose-li:text-muted-foreground">
            <h2>Acceptance of Terms</h2>
            <p>By accessing and using Psych Report Assistant ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.</p>
            <h2>Description of Service</h2>
            <p>Psych Report Assistant provides a free tool for generating psychological assessment reports from Q-Global export files. The Service processes files locally in your browser and does not store or transmit your data.</p>
            <h2>Use of Service</h2>
            <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You are responsible for ensuring your use complies with applicable laws, including FERPA and other privacy regulations.</p>
            <h2>Professional Responsibility</h2>
            <p>Reports generated by this tool are templates requiring professional review and customization. You, as a licensed professional, are solely responsible for the accuracy and appropriateness of any reports you produce and distribute.</p>
            <h2>Intellectual Property</h2>
            <p>The Service, including its design, features, and content, is owned by Psych Report Assistant. You may not copy, modify, or distribute our Service without permission.</p>
            <h2>Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of generated reports. Professional judgment is required for all assessment interpretations.</p>
            <h2>Limitation of Liability</h2>
            <p>Psych Report Assistant shall not be liable for any damages arising from your use of the Service, including but not limited to errors in generated reports or professional decisions made based on those reports.</p>
            <h2>Modifications</h2>
            <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of new terms.</p>
            <h2>Contact</h2>
            <p>For questions about these Terms, please contact us at info@psychreportassistant.com.</p>
          </div>
        </div>
      </section>
    </Layout>
  );
}
